var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/products/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1p2ehpm._.js")
R.c("server/chunks/ssr/1e8u_next_dist_esm_build_templates_app-page_1ik7tsf.js")
R.c("server/chunks/ssr/[root-of-the-server]__1nzcliw._.js")
R.c("server/chunks/ssr/1e8u_next_dist_1twtdy-._.js")
R.c("server/chunks/ssr/0sj1_@opentelemetry_api_build_esm_0sllqks._.js")
R.c("server/chunks/ssr/apps_web_components_sections_ClaimYourGrowth_tsx_1ks9_ov._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1dqnrp8._.js")
R.c("server/chunks/ssr/apps_web_app_error_tsx_09htp1j._.js")
R.c("server/chunks/ssr/apps_web_app_template_tsx_0xjo31q._.js")
R.c("server/chunks/ssr/apps_web_1_73w-p._.js")
R.c("server/chunks/ssr/1e8u_next_dist_client_components_051y1ga._.js")
R.c("server/chunks/ssr/1e8u_next_dist_client_components_builtin_unauthorized_17jclba.js")
R.c("server/chunks/ssr/apps_web_app_global-error_tsx_1d15na6._.js")
R.c("server/chunks/ssr/apps_web_app_products_loading_tsx_0tjckad._.js")
R.c("server/chunks/ssr/apps_web__next-internal_server_app_products_page_actions_11o80f5.js")
R.m(37145)
module.exports=R.m(37145).exports
