apiVersion: v1
kind: Service
metadata:
  name: tradingo-web
  namespace: tradingo
  labels:
    app: tradingo-web
    app.kubernetes.io/name: tradingo-web
    app.kubernetes.io/part-of: tradingo-platform
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
  selector:
    app: tradingo-web
