export type Role = 'SUPER_ADMIN' | 'ADMIN' | 'MANAGER' | 'SELLER' | 'BUYER' | 'VIEWER';

export type AdStatus = 'DRAFT' | 'PENDING_REVIEW' | 'ACTIVE' | 'PAUSED' | 'EXPIRED' | 'CANCELLED' | 'REJECTED' | 'COMPLETED';

export type AdType = 'SPONSORED_PRODUCT' | 'SPONSORED_COMPANY' | 'SPONSORED_CATEGORY' | 'HOMEPAGE_BANNER' | 'CATEGORY_BANNER' | 'SEARCH_KEYWORD_AD' | 'CITY_PROMOTION' | 'FEATURED_SELLER' | 'FEATURED_BRAND';

export type AdPricingModel = 'CPC' | 'CPM' | 'FIXED';

export type AdTargetType = 'COUNTRY' | 'STATE' | 'CITY' | 'CATEGORY' | 'PRODUCT' | 'KEYWORD' | 'INDUSTRY';

export type OrderStatus = 'PENDING' | 'CONFIRMED' | 'PROCESSING' | 'PACKED' | 'READY_FOR_DISPATCH' | 'DISPATCHED' | 'IN_TRANSIT' | 'DELIVERED' | 'COMPLETED' | 'CANCELLED' | 'RETURNED';

export type ProductStatus = 'DRAFT' | 'ACTIVE' | 'INACTIVE' | 'OUT_OF_STOCK' | 'DISCONTINUED' | 'PENDING_APPROVAL' | 'REJECTED';

export type CampaignStatus = 'DRAFT' | 'ACTIVE' | 'PAUSED' | 'COMPLETED' | 'CANCELLED' | 'ARCHIVED' | 'EXPIRED';

export type VerificationStatus = 'PENDING' | 'APPROVED' | 'REJECTED';

export type VerificationLevel = 'LEVEL_0' | 'LEVEL_1' | 'LEVEL_2' | 'LEVEL_3' | 'LEVEL_4' | 'LEVEL_5' | 'LEVEL_6';

export type SubscriptionStatus = 'TRIAL' | 'ACTIVE' | 'EXPIRED' | 'SUSPENDED' | 'CANCELLED';

export type EscrowStatus = 'PENDING' | 'HELD' | 'PARTIALLY_RELEASED' | 'RELEASED' | 'REFUND_PENDING' | 'REFUNDED' | 'DISPUTED' | 'CANCELLED' | 'FAILED' | 'FROZEN' | 'MANUAL_REVIEW';

export type DisputeStatus = 'OPEN' | 'UNDER_REVIEW' | 'EVIDENCE_PENDING' | 'NEGOTIATION' | 'ESCALATED' | 'ADMIN_ARBITRATION' | 'PARTIALLY_RESOLVED' | 'RESOLVED' | 'REFUNDED' | 'REJECTED' | 'CANCELLED' | 'EXPIRED' | 'APPEALED';

export type ShipmentStatus = 'PREPARING' | 'PACKED' | 'READY_FOR_PICKUP' | 'COURIER_ASSIGNED' | 'DISPATCHED' | 'IN_TRANSIT' | 'OUT_FOR_DELIVERY' | 'DELIVERED' | 'DELIVERY_FAILED' | 'RETURNED';
